apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-server-deployment
  labels:
    app: worker-server
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-server
      type: backend
  template:
    metadata:
      labels:
        app: worker-server
        type: backend
    spec:
      containers:
        - name: worker-server-container
          image: kratoscontains/demucs-worker-try:latest
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "11Gi"