apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server-deployment
  labels:
    app: rest-server
    type: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
      type: api-server
  template:
    metadata:
      labels:
        app: rest-server
        type: api-server
    spec:
      containers:
        - name: rest-server-container
          image: kratoscontains/demucs-rest-try:v1
          ports:
            - containerPort: 5000