apiVersion: v1
kind: Service
metadata:
  name: rest-service
  labels:
    app: api-server
spec:
  type: NodePort
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: rest-server